// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

#ifndef PROTOBUF_model_2eproto__INCLUDED
#define PROTOBUF_model_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_model_2eproto();
void protobuf_AssignDesc_model_2eproto();
void protobuf_ShutdownFile_model_2eproto();

class Code;
class Point;
class Beacon;
class Environement;

enum Code_Type {
  Code_Type_Gold = 0,
  Code_Type_Kasami = 1,
  Code_Type_Hadamard = 2
};
bool Code_Type_IsValid(int value);
const Code_Type Code_Type_Type_MIN = Code_Type_Gold;
const Code_Type Code_Type_Type_MAX = Code_Type_Hadamard;
const int Code_Type_Type_ARRAYSIZE = Code_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Code_Type_descriptor();
inline const ::std::string& Code_Type_Name(Code_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Code_Type_descriptor(), value);
}
inline bool Code_Type_Parse(
    const ::std::string& name, Code_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Code_Type>(
    Code_Type_descriptor(), name, value);
}
// ===================================================================

class Code : public ::google::protobuf::Message {
 public:
  Code();
  virtual ~Code();
  
  Code(const Code& from);
  
  inline Code& operator=(const Code& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Code& default_instance();
  
  void Swap(Code* other);
  
  // implements Message ----------------------------------------------
  
  Code* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Code& from);
  void MergeFrom(const Code& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Code_Type Type;
  static const Type Gold = Code_Type_Gold;
  static const Type Kasami = Code_Type_Kasami;
  static const Type Hadamard = Code_Type_Hadamard;
  static inline bool Type_IsValid(int value) {
    return Code_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Code_Type_Type_MIN;
  static const Type Type_MAX =
    Code_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Code_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Code_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Code_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Code_Type_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required .Code.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::Code_Type type() const;
  inline void set_type(::Code_Type value);
  
  // required uint32 order = 2;
  inline bool has_order() const;
  inline void clear_order();
  static const int kOrderFieldNumber = 2;
  inline ::google::protobuf::uint32 order() const;
  inline void set_order(::google::protobuf::uint32 value);
  
  // repeated float data = 3;
  inline int data_size() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline float data(int index) const;
  inline void set_data(int index, float value);
  inline void add_data(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      data() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_data();
  
  // @@protoc_insertion_point(class_scope:Code)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_order();
  inline void clear_has_order();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  int type_;
  ::google::protobuf::uint32 order_;
  ::google::protobuf::RepeatedField< float > data_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_model_2eproto();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();
  
  void InitAsDefaultInstance();
  static Code* default_instance_;
};
// -------------------------------------------------------------------

class Point : public ::google::protobuf::Message {
 public:
  Point();
  virtual ~Point();
  
  Point(const Point& from);
  
  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Point& default_instance();
  
  void Swap(Point* other);
  
  // implements Message ----------------------------------------------
  
  Point* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);
  
  // required float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);
  
  // required float z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline float z() const;
  inline void set_z(float value);
  
  // @@protoc_insertion_point(class_scope:Point)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float x_;
  float y_;
  float z_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_model_2eproto();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();
  
  void InitAsDefaultInstance();
  static Point* default_instance_;
};
// -------------------------------------------------------------------

class Beacon : public ::google::protobuf::Message {
 public:
  Beacon();
  virtual ~Beacon();
  
  Beacon(const Beacon& from);
  
  inline Beacon& operator=(const Beacon& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Beacon& default_instance();
  
  void Swap(Beacon* other);
  
  // implements Message ----------------------------------------------
  
  Beacon* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Beacon& from);
  void MergeFrom(const Beacon& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);
  
  // required string uuid = 2;
  inline bool has_uuid() const;
  inline void clear_uuid();
  static const int kUuidFieldNumber = 2;
  inline const ::std::string& uuid() const;
  inline void set_uuid(const ::std::string& value);
  inline void set_uuid(const char* value);
  inline void set_uuid(const char* value, size_t size);
  inline ::std::string* mutable_uuid();
  inline ::std::string* release_uuid();
  
  // required float snr = 3;
  inline bool has_snr() const;
  inline void clear_snr();
  static const int kSnrFieldNumber = 3;
  inline float snr() const;
  inline void set_snr(float value);
  
  // required .Point point = 4;
  inline bool has_point() const;
  inline void clear_point();
  static const int kPointFieldNumber = 4;
  inline const ::Point& point() const;
  inline ::Point* mutable_point();
  inline ::Point* release_point();
  
  // required .Code code = 5;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 5;
  inline const ::Code& code() const;
  inline ::Code* mutable_code();
  inline ::Code* release_code();
  
  // required bool enabled = 6;
  inline bool has_enabled() const;
  inline void clear_enabled();
  static const int kEnabledFieldNumber = 6;
  inline bool enabled() const;
  inline void set_enabled(bool value);
  
  // optional string name = 7;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 7;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // @@protoc_insertion_point(class_scope:Beacon)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_uuid();
  inline void clear_has_uuid();
  inline void set_has_snr();
  inline void clear_has_snr();
  inline void set_has_point();
  inline void clear_has_point();
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_enabled();
  inline void clear_has_enabled();
  inline void set_has_name();
  inline void clear_has_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* uuid_;
  ::google::protobuf::uint32 id_;
  float snr_;
  ::Point* point_;
  ::Code* code_;
  ::std::string* name_;
  bool enabled_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];
  
  friend void  protobuf_AddDesc_model_2eproto();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();
  
  void InitAsDefaultInstance();
  static Beacon* default_instance_;
};
// -------------------------------------------------------------------

class Environement : public ::google::protobuf::Message {
 public:
  Environement();
  virtual ~Environement();
  
  Environement(const Environement& from);
  
  inline Environement& operator=(const Environement& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Environement& default_instance();
  
  void Swap(Environement* other);
  
  // implements Message ----------------------------------------------
  
  Environement* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Environement& from);
  void MergeFrom(const Environement& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);
  
  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // required string latitude = 3;
  inline bool has_latitude() const;
  inline void clear_latitude();
  static const int kLatitudeFieldNumber = 3;
  inline const ::std::string& latitude() const;
  inline void set_latitude(const ::std::string& value);
  inline void set_latitude(const char* value);
  inline void set_latitude(const char* value, size_t size);
  inline ::std::string* mutable_latitude();
  inline ::std::string* release_latitude();
  
  // required string longitud = 4;
  inline bool has_longitud() const;
  inline void clear_longitud();
  static const int kLongitudFieldNumber = 4;
  inline const ::std::string& longitud() const;
  inline void set_longitud(const ::std::string& value);
  inline void set_longitud(const char* value);
  inline void set_longitud(const char* value, size_t size);
  inline ::std::string* mutable_longitud();
  inline ::std::string* release_longitud();
  
  // repeated .Beacon beacons = 5;
  inline int beacons_size() const;
  inline void clear_beacons();
  static const int kBeaconsFieldNumber = 5;
  inline const ::Beacon& beacons(int index) const;
  inline ::Beacon* mutable_beacons(int index);
  inline ::Beacon* add_beacons();
  inline const ::google::protobuf::RepeatedPtrField< ::Beacon >&
      beacons() const;
  inline ::google::protobuf::RepeatedPtrField< ::Beacon >*
      mutable_beacons();
  
  // required float width = 6;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 6;
  inline float width() const;
  inline void set_width(float value);
  
  // required float length = 7;
  inline bool has_length() const;
  inline void clear_length();
  static const int kLengthFieldNumber = 7;
  inline float length() const;
  inline void set_length(float value);
  
  // required float height = 8;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 8;
  inline float height() const;
  inline void set_height(float value);
  
  // @@protoc_insertion_point(class_scope:Environement)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_latitude();
  inline void clear_has_latitude();
  inline void set_has_longitud();
  inline void clear_has_longitud();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_length();
  inline void clear_has_length();
  inline void set_has_height();
  inline void clear_has_height();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::std::string* latitude_;
  ::google::protobuf::uint32 id_;
  float width_;
  ::std::string* longitud_;
  ::google::protobuf::RepeatedPtrField< ::Beacon > beacons_;
  float length_;
  float height_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];
  
  friend void  protobuf_AddDesc_model_2eproto();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();
  
  void InitAsDefaultInstance();
  static Environement* default_instance_;
};
// ===================================================================


// ===================================================================

// Code

// required .Code.Type type = 1;
inline bool Code::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Code::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Code::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Code::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::Code_Type Code::type() const {
  return static_cast< ::Code_Type >(type_);
}
inline void Code::set_type(::Code_Type value) {
  GOOGLE_DCHECK(::Code_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// required uint32 order = 2;
inline bool Code::has_order() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Code::set_has_order() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Code::clear_has_order() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Code::clear_order() {
  order_ = 0u;
  clear_has_order();
}
inline ::google::protobuf::uint32 Code::order() const {
  return order_;
}
inline void Code::set_order(::google::protobuf::uint32 value) {
  set_has_order();
  order_ = value;
}

// repeated float data = 3;
inline int Code::data_size() const {
  return data_.size();
}
inline void Code::clear_data() {
  data_.Clear();
}
inline float Code::data(int index) const {
  return data_.Get(index);
}
inline void Code::set_data(int index, float value) {
  data_.Set(index, value);
}
inline void Code::add_data(float value) {
  data_.Add(value);
}
inline const ::google::protobuf::RepeatedField< float >&
Code::data() const {
  return data_;
}
inline ::google::protobuf::RepeatedField< float >*
Code::mutable_data() {
  return &data_;
}

// -------------------------------------------------------------------

// Point

// required float x = 1;
inline bool Point::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Point::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Point::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Point::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Point::x() const {
  return x_;
}
inline void Point::set_x(float value) {
  set_has_x();
  x_ = value;
}

// required float y = 2;
inline bool Point::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Point::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Point::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Point::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Point::y() const {
  return y_;
}
inline void Point::set_y(float value) {
  set_has_y();
  y_ = value;
}

// required float z = 3;
inline bool Point::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Point::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Point::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Point::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float Point::z() const {
  return z_;
}
inline void Point::set_z(float value) {
  set_has_z();
  z_ = value;
}

// -------------------------------------------------------------------

// Beacon

// required uint32 id = 1;
inline bool Beacon::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Beacon::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Beacon::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Beacon::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 Beacon::id() const {
  return id_;
}
inline void Beacon::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required string uuid = 2;
inline bool Beacon::has_uuid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Beacon::set_has_uuid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Beacon::clear_has_uuid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Beacon::clear_uuid() {
  if (uuid_ != &::google::protobuf::internal::kEmptyString) {
    uuid_->clear();
  }
  clear_has_uuid();
}
inline const ::std::string& Beacon::uuid() const {
  return *uuid_;
}
inline void Beacon::set_uuid(const ::std::string& value) {
  set_has_uuid();
  if (uuid_ == &::google::protobuf::internal::kEmptyString) {
    uuid_ = new ::std::string;
  }
  uuid_->assign(value);
}
inline void Beacon::set_uuid(const char* value) {
  set_has_uuid();
  if (uuid_ == &::google::protobuf::internal::kEmptyString) {
    uuid_ = new ::std::string;
  }
  uuid_->assign(value);
}
inline void Beacon::set_uuid(const char* value, size_t size) {
  set_has_uuid();
  if (uuid_ == &::google::protobuf::internal::kEmptyString) {
    uuid_ = new ::std::string;
  }
  uuid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Beacon::mutable_uuid() {
  set_has_uuid();
  if (uuid_ == &::google::protobuf::internal::kEmptyString) {
    uuid_ = new ::std::string;
  }
  return uuid_;
}
inline ::std::string* Beacon::release_uuid() {
  clear_has_uuid();
  if (uuid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = uuid_;
    uuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required float snr = 3;
inline bool Beacon::has_snr() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Beacon::set_has_snr() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Beacon::clear_has_snr() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Beacon::clear_snr() {
  snr_ = 0;
  clear_has_snr();
}
inline float Beacon::snr() const {
  return snr_;
}
inline void Beacon::set_snr(float value) {
  set_has_snr();
  snr_ = value;
}

// required .Point point = 4;
inline bool Beacon::has_point() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Beacon::set_has_point() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Beacon::clear_has_point() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Beacon::clear_point() {
  if (point_ != NULL) point_->::Point::Clear();
  clear_has_point();
}
inline const ::Point& Beacon::point() const {
  return point_ != NULL ? *point_ : *default_instance_->point_;
}
inline ::Point* Beacon::mutable_point() {
  set_has_point();
  if (point_ == NULL) point_ = new ::Point;
  return point_;
}
inline ::Point* Beacon::release_point() {
  clear_has_point();
  ::Point* temp = point_;
  point_ = NULL;
  return temp;
}

// required .Code code = 5;
inline bool Beacon::has_code() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Beacon::set_has_code() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Beacon::clear_has_code() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Beacon::clear_code() {
  if (code_ != NULL) code_->::Code::Clear();
  clear_has_code();
}
inline const ::Code& Beacon::code() const {
  return code_ != NULL ? *code_ : *default_instance_->code_;
}
inline ::Code* Beacon::mutable_code() {
  set_has_code();
  if (code_ == NULL) code_ = new ::Code;
  return code_;
}
inline ::Code* Beacon::release_code() {
  clear_has_code();
  ::Code* temp = code_;
  code_ = NULL;
  return temp;
}

// required bool enabled = 6;
inline bool Beacon::has_enabled() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Beacon::set_has_enabled() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Beacon::clear_has_enabled() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Beacon::clear_enabled() {
  enabled_ = false;
  clear_has_enabled();
}
inline bool Beacon::enabled() const {
  return enabled_;
}
inline void Beacon::set_enabled(bool value) {
  set_has_enabled();
  enabled_ = value;
}

// optional string name = 7;
inline bool Beacon::has_name() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Beacon::set_has_name() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Beacon::clear_has_name() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Beacon::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Beacon::name() const {
  return *name_;
}
inline void Beacon::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Beacon::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Beacon::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Beacon::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Beacon::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// Environement

// required uint32 id = 1;
inline bool Environement::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Environement::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Environement::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Environement::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 Environement::id() const {
  return id_;
}
inline void Environement::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required string name = 2;
inline bool Environement::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Environement::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Environement::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Environement::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Environement::name() const {
  return *name_;
}
inline void Environement::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Environement::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Environement::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Environement::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Environement::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string latitude = 3;
inline bool Environement::has_latitude() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Environement::set_has_latitude() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Environement::clear_has_latitude() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Environement::clear_latitude() {
  if (latitude_ != &::google::protobuf::internal::kEmptyString) {
    latitude_->clear();
  }
  clear_has_latitude();
}
inline const ::std::string& Environement::latitude() const {
  return *latitude_;
}
inline void Environement::set_latitude(const ::std::string& value) {
  set_has_latitude();
  if (latitude_ == &::google::protobuf::internal::kEmptyString) {
    latitude_ = new ::std::string;
  }
  latitude_->assign(value);
}
inline void Environement::set_latitude(const char* value) {
  set_has_latitude();
  if (latitude_ == &::google::protobuf::internal::kEmptyString) {
    latitude_ = new ::std::string;
  }
  latitude_->assign(value);
}
inline void Environement::set_latitude(const char* value, size_t size) {
  set_has_latitude();
  if (latitude_ == &::google::protobuf::internal::kEmptyString) {
    latitude_ = new ::std::string;
  }
  latitude_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Environement::mutable_latitude() {
  set_has_latitude();
  if (latitude_ == &::google::protobuf::internal::kEmptyString) {
    latitude_ = new ::std::string;
  }
  return latitude_;
}
inline ::std::string* Environement::release_latitude() {
  clear_has_latitude();
  if (latitude_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = latitude_;
    latitude_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string longitud = 4;
inline bool Environement::has_longitud() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Environement::set_has_longitud() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Environement::clear_has_longitud() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Environement::clear_longitud() {
  if (longitud_ != &::google::protobuf::internal::kEmptyString) {
    longitud_->clear();
  }
  clear_has_longitud();
}
inline const ::std::string& Environement::longitud() const {
  return *longitud_;
}
inline void Environement::set_longitud(const ::std::string& value) {
  set_has_longitud();
  if (longitud_ == &::google::protobuf::internal::kEmptyString) {
    longitud_ = new ::std::string;
  }
  longitud_->assign(value);
}
inline void Environement::set_longitud(const char* value) {
  set_has_longitud();
  if (longitud_ == &::google::protobuf::internal::kEmptyString) {
    longitud_ = new ::std::string;
  }
  longitud_->assign(value);
}
inline void Environement::set_longitud(const char* value, size_t size) {
  set_has_longitud();
  if (longitud_ == &::google::protobuf::internal::kEmptyString) {
    longitud_ = new ::std::string;
  }
  longitud_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Environement::mutable_longitud() {
  set_has_longitud();
  if (longitud_ == &::google::protobuf::internal::kEmptyString) {
    longitud_ = new ::std::string;
  }
  return longitud_;
}
inline ::std::string* Environement::release_longitud() {
  clear_has_longitud();
  if (longitud_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = longitud_;
    longitud_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .Beacon beacons = 5;
inline int Environement::beacons_size() const {
  return beacons_.size();
}
inline void Environement::clear_beacons() {
  beacons_.Clear();
}
inline const ::Beacon& Environement::beacons(int index) const {
  return beacons_.Get(index);
}
inline ::Beacon* Environement::mutable_beacons(int index) {
  return beacons_.Mutable(index);
}
inline ::Beacon* Environement::add_beacons() {
  return beacons_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Beacon >&
Environement::beacons() const {
  return beacons_;
}
inline ::google::protobuf::RepeatedPtrField< ::Beacon >*
Environement::mutable_beacons() {
  return &beacons_;
}

// required float width = 6;
inline bool Environement::has_width() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Environement::set_has_width() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Environement::clear_has_width() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Environement::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline float Environement::width() const {
  return width_;
}
inline void Environement::set_width(float value) {
  set_has_width();
  width_ = value;
}

// required float length = 7;
inline bool Environement::has_length() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Environement::set_has_length() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Environement::clear_has_length() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Environement::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline float Environement::length() const {
  return length_;
}
inline void Environement::set_length(float value) {
  set_has_length();
  length_ = value;
}

// required float height = 8;
inline bool Environement::has_height() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Environement::set_has_height() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Environement::clear_has_height() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Environement::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline float Environement::height() const {
  return height_;
}
inline void Environement::set_height(float value) {
  set_has_height();
  height_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Code_Type>() {
  return ::Code_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_model_2eproto__INCLUDED
