// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

#ifndef PROTOBUF_model_2eproto__INCLUDED
#define PROTOBUF_model_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_model_2eproto();
void protobuf_InitDefaults_model_2eproto();
void protobuf_AssignDesc_model_2eproto();
void protobuf_ShutdownFile_model_2eproto();

class Beacon;
class Code;
class Environement;
class Point;

enum Code_Type {
  Code_Type_Gold = 0,
  Code_Type_Kasami = 1,
  Code_Type_Hadamard = 2,
  Code_Type_Code_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Code_Type_Code_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Code_Type_IsValid(int value);
const Code_Type Code_Type_Type_MIN = Code_Type_Gold;
const Code_Type Code_Type_Type_MAX = Code_Type_Hadamard;
const int Code_Type_Type_ARRAYSIZE = Code_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Code_Type_descriptor();
inline const ::std::string& Code_Type_Name(Code_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Code_Type_descriptor(), value);
}
inline bool Code_Type_Parse(
    const ::std::string& name, Code_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Code_Type>(
    Code_Type_descriptor(), name, value);
}
// ===================================================================

class Code : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Code) */ {
 public:
  Code();
  virtual ~Code();

  Code(const Code& from);

  inline Code& operator=(const Code& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Code& default_instance();

  static const Code* internal_default_instance();

  void Swap(Code* other);

  // implements Message ----------------------------------------------

  inline Code* New() const { return New(NULL); }

  Code* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Code& from);
  void MergeFrom(const Code& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Code* other);
  void UnsafeMergeFrom(const Code& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Code_Type Type;
  static const Type Gold =
    Code_Type_Gold;
  static const Type Kasami =
    Code_Type_Kasami;
  static const Type Hadamard =
    Code_Type_Hadamard;
  static inline bool Type_IsValid(int value) {
    return Code_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Code_Type_Type_MIN;
  static const Type Type_MAX =
    Code_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Code_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Code_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Code_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Code_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .Code.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::Code_Type type() const;
  void set_type(::Code_Type value);

  // optional uint32 order = 2;
  void clear_order();
  static const int kOrderFieldNumber = 2;
  ::google::protobuf::uint32 order() const;
  void set_order(::google::protobuf::uint32 value);

  // repeated float data = 3;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 3;
  float data(int index) const;
  void set_data(int index, float value);
  void add_data(float value);
  const ::google::protobuf::RepeatedField< float >&
      data() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_data();

  // @@protoc_insertion_point(class_scope:Code)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > data_;
  mutable int _data_cached_byte_size_;
  int type_;
  ::google::protobuf::uint32 order_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_model_2eproto_impl();
  friend void  protobuf_AddDesc_model_2eproto_impl();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Code> Code_default_instance_;

// -------------------------------------------------------------------

class Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Point) */ {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Point& default_instance();

  static const Point* internal_default_instance();

  void Swap(Point* other);

  // implements Message ----------------------------------------------

  inline Point* New() const { return New(NULL); }

  Point* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Point* other);
  void UnsafeMergeFrom(const Point& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // optional float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:Point)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_model_2eproto_impl();
  friend void  protobuf_AddDesc_model_2eproto_impl();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Point> Point_default_instance_;

// -------------------------------------------------------------------

class Beacon : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Beacon) */ {
 public:
  Beacon();
  virtual ~Beacon();

  Beacon(const Beacon& from);

  inline Beacon& operator=(const Beacon& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Beacon& default_instance();

  static const Beacon* internal_default_instance();

  void Swap(Beacon* other);

  // implements Message ----------------------------------------------

  inline Beacon* New() const { return New(NULL); }

  Beacon* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Beacon& from);
  void MergeFrom(const Beacon& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Beacon* other);
  void UnsafeMergeFrom(const Beacon& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional string uuid = 2;
  void clear_uuid();
  static const int kUuidFieldNumber = 2;
  const ::std::string& uuid() const;
  void set_uuid(const ::std::string& value);
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  ::std::string* mutable_uuid();
  ::std::string* release_uuid();
  void set_allocated_uuid(::std::string* uuid);

  // optional float snr = 3;
  void clear_snr();
  static const int kSnrFieldNumber = 3;
  float snr() const;
  void set_snr(float value);

  // optional .Point point = 4;
  bool has_point() const;
  void clear_point();
  static const int kPointFieldNumber = 4;
  const ::Point& point() const;
  ::Point* mutable_point();
  ::Point* release_point();
  void set_allocated_point(::Point* point);

  // optional .Code code = 5;
  bool has_code() const;
  void clear_code();
  static const int kCodeFieldNumber = 5;
  const ::Code& code() const;
  ::Code* mutable_code();
  ::Code* release_code();
  void set_allocated_code(::Code* code);

  // optional bool enabled = 6;
  void clear_enabled();
  static const int kEnabledFieldNumber = 6;
  bool enabled() const;
  void set_enabled(bool value);

  // optional string name = 7;
  void clear_name();
  static const int kNameFieldNumber = 7;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:Beacon)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr uuid_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::Point* point_;
  ::Code* code_;
  ::google::protobuf::uint32 id_;
  float snr_;
  bool enabled_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_model_2eproto_impl();
  friend void  protobuf_AddDesc_model_2eproto_impl();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Beacon> Beacon_default_instance_;

// -------------------------------------------------------------------

class Environement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Environement) */ {
 public:
  Environement();
  virtual ~Environement();

  Environement(const Environement& from);

  inline Environement& operator=(const Environement& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Environement& default_instance();

  static const Environement* internal_default_instance();

  void Swap(Environement* other);

  // implements Message ----------------------------------------------

  inline Environement* New() const { return New(NULL); }

  Environement* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Environement& from);
  void MergeFrom(const Environement& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Environement* other);
  void UnsafeMergeFrom(const Environement& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string latitude = 3;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 3;
  const ::std::string& latitude() const;
  void set_latitude(const ::std::string& value);
  void set_latitude(const char* value);
  void set_latitude(const char* value, size_t size);
  ::std::string* mutable_latitude();
  ::std::string* release_latitude();
  void set_allocated_latitude(::std::string* latitude);

  // optional string longitud = 4;
  void clear_longitud();
  static const int kLongitudFieldNumber = 4;
  const ::std::string& longitud() const;
  void set_longitud(const ::std::string& value);
  void set_longitud(const char* value);
  void set_longitud(const char* value, size_t size);
  ::std::string* mutable_longitud();
  ::std::string* release_longitud();
  void set_allocated_longitud(::std::string* longitud);

  // repeated .Beacon beacons = 5;
  int beacons_size() const;
  void clear_beacons();
  static const int kBeaconsFieldNumber = 5;
  const ::Beacon& beacons(int index) const;
  ::Beacon* mutable_beacons(int index);
  ::Beacon* add_beacons();
  ::google::protobuf::RepeatedPtrField< ::Beacon >*
      mutable_beacons();
  const ::google::protobuf::RepeatedPtrField< ::Beacon >&
      beacons() const;

  // optional float width = 6;
  void clear_width();
  static const int kWidthFieldNumber = 6;
  float width() const;
  void set_width(float value);

  // optional float length = 7;
  void clear_length();
  static const int kLengthFieldNumber = 7;
  float length() const;
  void set_length(float value);

  // optional float height = 8;
  void clear_height();
  static const int kHeightFieldNumber = 8;
  float height() const;
  void set_height(float value);

  // @@protoc_insertion_point(class_scope:Environement)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Beacon > beacons_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr latitude_;
  ::google::protobuf::internal::ArenaStringPtr longitud_;
  ::google::protobuf::uint32 id_;
  float width_;
  float length_;
  float height_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_model_2eproto_impl();
  friend void  protobuf_AddDesc_model_2eproto_impl();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Environement> Environement_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Code

// optional .Code.Type type = 1;
inline void Code::clear_type() {
  type_ = 0;
}
inline ::Code_Type Code::type() const {
  // @@protoc_insertion_point(field_get:Code.type)
  return static_cast< ::Code_Type >(type_);
}
inline void Code::set_type(::Code_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Code.type)
}

// optional uint32 order = 2;
inline void Code::clear_order() {
  order_ = 0u;
}
inline ::google::protobuf::uint32 Code::order() const {
  // @@protoc_insertion_point(field_get:Code.order)
  return order_;
}
inline void Code::set_order(::google::protobuf::uint32 value) {
  
  order_ = value;
  // @@protoc_insertion_point(field_set:Code.order)
}

// repeated float data = 3;
inline int Code::data_size() const {
  return data_.size();
}
inline void Code::clear_data() {
  data_.Clear();
}
inline float Code::data(int index) const {
  // @@protoc_insertion_point(field_get:Code.data)
  return data_.Get(index);
}
inline void Code::set_data(int index, float value) {
  data_.Set(index, value);
  // @@protoc_insertion_point(field_set:Code.data)
}
inline void Code::add_data(float value) {
  data_.Add(value);
  // @@protoc_insertion_point(field_add:Code.data)
}
inline const ::google::protobuf::RepeatedField< float >&
Code::data() const {
  // @@protoc_insertion_point(field_list:Code.data)
  return data_;
}
inline ::google::protobuf::RepeatedField< float >*
Code::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:Code.data)
  return &data_;
}

inline const Code* Code::internal_default_instance() {
  return &Code_default_instance_.get();
}
// -------------------------------------------------------------------

// Point

// optional float x = 1;
inline void Point::clear_x() {
  x_ = 0;
}
inline float Point::x() const {
  // @@protoc_insertion_point(field_get:Point.x)
  return x_;
}
inline void Point::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:Point.x)
}

// optional float y = 2;
inline void Point::clear_y() {
  y_ = 0;
}
inline float Point::y() const {
  // @@protoc_insertion_point(field_get:Point.y)
  return y_;
}
inline void Point::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:Point.y)
}

// optional float z = 3;
inline void Point::clear_z() {
  z_ = 0;
}
inline float Point::z() const {
  // @@protoc_insertion_point(field_get:Point.z)
  return z_;
}
inline void Point::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:Point.z)
}

inline const Point* Point::internal_default_instance() {
  return &Point_default_instance_.get();
}
// -------------------------------------------------------------------

// Beacon

// optional uint32 id = 1;
inline void Beacon::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 Beacon::id() const {
  // @@protoc_insertion_point(field_get:Beacon.id)
  return id_;
}
inline void Beacon::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Beacon.id)
}

// optional string uuid = 2;
inline void Beacon::clear_uuid() {
  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Beacon::uuid() const {
  // @@protoc_insertion_point(field_get:Beacon.uuid)
  return uuid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Beacon::set_uuid(const ::std::string& value) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Beacon.uuid)
}
inline void Beacon::set_uuid(const char* value) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Beacon.uuid)
}
inline void Beacon::set_uuid(const char* value, size_t size) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Beacon.uuid)
}
inline ::std::string* Beacon::mutable_uuid() {
  
  // @@protoc_insertion_point(field_mutable:Beacon.uuid)
  return uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Beacon::release_uuid() {
  // @@protoc_insertion_point(field_release:Beacon.uuid)
  
  return uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Beacon::set_allocated_uuid(::std::string* uuid) {
  if (uuid != NULL) {
    
  } else {
    
  }
  uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uuid);
  // @@protoc_insertion_point(field_set_allocated:Beacon.uuid)
}

// optional float snr = 3;
inline void Beacon::clear_snr() {
  snr_ = 0;
}
inline float Beacon::snr() const {
  // @@protoc_insertion_point(field_get:Beacon.snr)
  return snr_;
}
inline void Beacon::set_snr(float value) {
  
  snr_ = value;
  // @@protoc_insertion_point(field_set:Beacon.snr)
}

// optional .Point point = 4;
inline bool Beacon::has_point() const {
  return this != internal_default_instance() && point_ != NULL;
}
inline void Beacon::clear_point() {
  if (GetArenaNoVirtual() == NULL && point_ != NULL) delete point_;
  point_ = NULL;
}
inline const ::Point& Beacon::point() const {
  // @@protoc_insertion_point(field_get:Beacon.point)
  return point_ != NULL ? *point_
                         : *::Point::internal_default_instance();
}
inline ::Point* Beacon::mutable_point() {
  
  if (point_ == NULL) {
    point_ = new ::Point;
  }
  // @@protoc_insertion_point(field_mutable:Beacon.point)
  return point_;
}
inline ::Point* Beacon::release_point() {
  // @@protoc_insertion_point(field_release:Beacon.point)
  
  ::Point* temp = point_;
  point_ = NULL;
  return temp;
}
inline void Beacon::set_allocated_point(::Point* point) {
  delete point_;
  point_ = point;
  if (point) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Beacon.point)
}

// optional .Code code = 5;
inline bool Beacon::has_code() const {
  return this != internal_default_instance() && code_ != NULL;
}
inline void Beacon::clear_code() {
  if (GetArenaNoVirtual() == NULL && code_ != NULL) delete code_;
  code_ = NULL;
}
inline const ::Code& Beacon::code() const {
  // @@protoc_insertion_point(field_get:Beacon.code)
  return code_ != NULL ? *code_
                         : *::Code::internal_default_instance();
}
inline ::Code* Beacon::mutable_code() {
  
  if (code_ == NULL) {
    code_ = new ::Code;
  }
  // @@protoc_insertion_point(field_mutable:Beacon.code)
  return code_;
}
inline ::Code* Beacon::release_code() {
  // @@protoc_insertion_point(field_release:Beacon.code)
  
  ::Code* temp = code_;
  code_ = NULL;
  return temp;
}
inline void Beacon::set_allocated_code(::Code* code) {
  delete code_;
  code_ = code;
  if (code) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Beacon.code)
}

// optional bool enabled = 6;
inline void Beacon::clear_enabled() {
  enabled_ = false;
}
inline bool Beacon::enabled() const {
  // @@protoc_insertion_point(field_get:Beacon.enabled)
  return enabled_;
}
inline void Beacon::set_enabled(bool value) {
  
  enabled_ = value;
  // @@protoc_insertion_point(field_set:Beacon.enabled)
}

// optional string name = 7;
inline void Beacon::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Beacon::name() const {
  // @@protoc_insertion_point(field_get:Beacon.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Beacon::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Beacon.name)
}
inline void Beacon::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Beacon.name)
}
inline void Beacon::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Beacon.name)
}
inline ::std::string* Beacon::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Beacon.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Beacon::release_name() {
  // @@protoc_insertion_point(field_release:Beacon.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Beacon::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Beacon.name)
}

inline const Beacon* Beacon::internal_default_instance() {
  return &Beacon_default_instance_.get();
}
// -------------------------------------------------------------------

// Environement

// optional uint32 id = 1;
inline void Environement::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 Environement::id() const {
  // @@protoc_insertion_point(field_get:Environement.id)
  return id_;
}
inline void Environement::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Environement.id)
}

// optional string name = 2;
inline void Environement::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Environement::name() const {
  // @@protoc_insertion_point(field_get:Environement.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Environement::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Environement.name)
}
inline void Environement::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Environement.name)
}
inline void Environement::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Environement.name)
}
inline ::std::string* Environement::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Environement.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Environement::release_name() {
  // @@protoc_insertion_point(field_release:Environement.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Environement::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Environement.name)
}

// optional string latitude = 3;
inline void Environement::clear_latitude() {
  latitude_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Environement::latitude() const {
  // @@protoc_insertion_point(field_get:Environement.latitude)
  return latitude_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Environement::set_latitude(const ::std::string& value) {
  
  latitude_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Environement.latitude)
}
inline void Environement::set_latitude(const char* value) {
  
  latitude_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Environement.latitude)
}
inline void Environement::set_latitude(const char* value, size_t size) {
  
  latitude_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Environement.latitude)
}
inline ::std::string* Environement::mutable_latitude() {
  
  // @@protoc_insertion_point(field_mutable:Environement.latitude)
  return latitude_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Environement::release_latitude() {
  // @@protoc_insertion_point(field_release:Environement.latitude)
  
  return latitude_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Environement::set_allocated_latitude(::std::string* latitude) {
  if (latitude != NULL) {
    
  } else {
    
  }
  latitude_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), latitude);
  // @@protoc_insertion_point(field_set_allocated:Environement.latitude)
}

// optional string longitud = 4;
inline void Environement::clear_longitud() {
  longitud_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Environement::longitud() const {
  // @@protoc_insertion_point(field_get:Environement.longitud)
  return longitud_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Environement::set_longitud(const ::std::string& value) {
  
  longitud_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Environement.longitud)
}
inline void Environement::set_longitud(const char* value) {
  
  longitud_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Environement.longitud)
}
inline void Environement::set_longitud(const char* value, size_t size) {
  
  longitud_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Environement.longitud)
}
inline ::std::string* Environement::mutable_longitud() {
  
  // @@protoc_insertion_point(field_mutable:Environement.longitud)
  return longitud_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Environement::release_longitud() {
  // @@protoc_insertion_point(field_release:Environement.longitud)
  
  return longitud_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Environement::set_allocated_longitud(::std::string* longitud) {
  if (longitud != NULL) {
    
  } else {
    
  }
  longitud_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), longitud);
  // @@protoc_insertion_point(field_set_allocated:Environement.longitud)
}

// repeated .Beacon beacons = 5;
inline int Environement::beacons_size() const {
  return beacons_.size();
}
inline void Environement::clear_beacons() {
  beacons_.Clear();
}
inline const ::Beacon& Environement::beacons(int index) const {
  // @@protoc_insertion_point(field_get:Environement.beacons)
  return beacons_.Get(index);
}
inline ::Beacon* Environement::mutable_beacons(int index) {
  // @@protoc_insertion_point(field_mutable:Environement.beacons)
  return beacons_.Mutable(index);
}
inline ::Beacon* Environement::add_beacons() {
  // @@protoc_insertion_point(field_add:Environement.beacons)
  return beacons_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Beacon >*
Environement::mutable_beacons() {
  // @@protoc_insertion_point(field_mutable_list:Environement.beacons)
  return &beacons_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Beacon >&
Environement::beacons() const {
  // @@protoc_insertion_point(field_list:Environement.beacons)
  return beacons_;
}

// optional float width = 6;
inline void Environement::clear_width() {
  width_ = 0;
}
inline float Environement::width() const {
  // @@protoc_insertion_point(field_get:Environement.width)
  return width_;
}
inline void Environement::set_width(float value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:Environement.width)
}

// optional float length = 7;
inline void Environement::clear_length() {
  length_ = 0;
}
inline float Environement::length() const {
  // @@protoc_insertion_point(field_get:Environement.length)
  return length_;
}
inline void Environement::set_length(float value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:Environement.length)
}

// optional float height = 8;
inline void Environement::clear_height() {
  height_ = 0;
}
inline float Environement::height() const {
  // @@protoc_insertion_point(field_get:Environement.height)
  return height_;
}
inline void Environement::set_height(float value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:Environement.height)
}

inline const Environement* Environement::internal_default_instance() {
  return &Environement_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Code_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Code_Type>() {
  return ::Code_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_model_2eproto__INCLUDED
