// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

#ifndef PROTOBUF_model_2eproto__INCLUDED
#define PROTOBUF_model_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class Beacon;
class BeaconDefaultTypeInternal;
extern BeaconDefaultTypeInternal _Beacon_default_instance_;
class Code;
class CodeDefaultTypeInternal;
extern CodeDefaultTypeInternal _Code_default_instance_;
class Environement;
class EnvironementDefaultTypeInternal;
extern EnvironementDefaultTypeInternal _Environement_default_instance_;
class Point;
class PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;

namespace protobuf_model_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_model_2eproto

enum Code_Type {
  Code_Type_Gold = 0,
  Code_Type_Kasami = 1,
  Code_Type_Hadamard = 2
};
bool Code_Type_IsValid(int value);
const Code_Type Code_Type_Type_MIN = Code_Type_Gold;
const Code_Type Code_Type_Type_MAX = Code_Type_Hadamard;
const int Code_Type_Type_ARRAYSIZE = Code_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Code_Type_descriptor();
inline const ::std::string& Code_Type_Name(Code_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Code_Type_descriptor(), value);
}
inline bool Code_Type_Parse(
    const ::std::string& name, Code_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Code_Type>(
    Code_Type_descriptor(), name, value);
}
// ===================================================================

class Code : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Code) */ {
 public:
  Code();
  virtual ~Code();

  Code(const Code& from);

  inline Code& operator=(const Code& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Code& default_instance();

  static inline const Code* internal_default_instance() {
    return reinterpret_cast<const Code*>(
               &_Code_default_instance_);
  }

  void Swap(Code* other);

  // implements Message ----------------------------------------------

  inline Code* New() const PROTOBUF_FINAL { return New(NULL); }

  Code* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Code& from);
  void MergeFrom(const Code& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Code* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Code_Type Type;
  static const Type Gold =
    Code_Type_Gold;
  static const Type Kasami =
    Code_Type_Kasami;
  static const Type Hadamard =
    Code_Type_Hadamard;
  static inline bool Type_IsValid(int value) {
    return Code_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Code_Type_Type_MIN;
  static const Type Type_MAX =
    Code_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Code_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Code_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Code_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Code_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated float data = 3;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 3;
  float data(int index) const;
  void set_data(int index, float value);
  void add_data(float value);
  const ::google::protobuf::RepeatedField< float >&
      data() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_data();

  // required .Code.Type type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::Code_Type type() const;
  void set_type(::Code_Type value);

  // required uint32 order = 2;
  bool has_order() const;
  void clear_order();
  static const int kOrderFieldNumber = 2;
  ::google::protobuf::uint32 order() const;
  void set_order(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Code)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_order();
  void clear_has_order();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > data_;
  int type_;
  ::google::protobuf::uint32 order_;
  friend struct  protobuf_model_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Point) */ {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Point& default_instance();

  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }

  void Swap(Point* other);

  // implements Message ----------------------------------------------

  inline Point* New() const PROTOBUF_FINAL { return New(NULL); }

  Point* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // required float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // required float z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:Point)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  float x_;
  float y_;
  float z_;
  friend struct  protobuf_model_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Beacon : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Beacon) */ {
 public:
  Beacon();
  virtual ~Beacon();

  Beacon(const Beacon& from);

  inline Beacon& operator=(const Beacon& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Beacon& default_instance();

  static inline const Beacon* internal_default_instance() {
    return reinterpret_cast<const Beacon*>(
               &_Beacon_default_instance_);
  }

  void Swap(Beacon* other);

  // implements Message ----------------------------------------------

  inline Beacon* New() const PROTOBUF_FINAL { return New(NULL); }

  Beacon* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Beacon& from);
  void MergeFrom(const Beacon& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Beacon* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string uuid = 2;
  bool has_uuid() const;
  void clear_uuid();
  static const int kUuidFieldNumber = 2;
  const ::std::string& uuid() const;
  void set_uuid(const ::std::string& value);
  #if LANG_CXX11
  void set_uuid(::std::string&& value);
  #endif
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  ::std::string* mutable_uuid();
  ::std::string* release_uuid();
  void set_allocated_uuid(::std::string* uuid);

  // optional string name = 7;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 7;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required .Point point = 4;
  bool has_point() const;
  void clear_point();
  static const int kPointFieldNumber = 4;
  const ::Point& point() const;
  ::Point* mutable_point();
  ::Point* release_point();
  void set_allocated_point(::Point* point);

  // required .Code code = 5;
  bool has_code() const;
  void clear_code();
  static const int kCodeFieldNumber = 5;
  const ::Code& code() const;
  ::Code* mutable_code();
  ::Code* release_code();
  void set_allocated_code(::Code* code);

  // required uint32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // required float snr = 3;
  bool has_snr() const;
  void clear_snr();
  static const int kSnrFieldNumber = 3;
  float snr() const;
  void set_snr(float value);

  // required bool enabled = 6;
  bool has_enabled() const;
  void clear_enabled();
  static const int kEnabledFieldNumber = 6;
  bool enabled() const;
  void set_enabled(bool value);

  // @@protoc_insertion_point(class_scope:Beacon)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_uuid();
  void clear_has_uuid();
  void set_has_snr();
  void clear_has_snr();
  void set_has_point();
  void clear_has_point();
  void set_has_code();
  void clear_has_code();
  void set_has_enabled();
  void clear_has_enabled();
  void set_has_name();
  void clear_has_name();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr uuid_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::Point* point_;
  ::Code* code_;
  ::google::protobuf::uint32 id_;
  float snr_;
  bool enabled_;
  friend struct  protobuf_model_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Environement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Environement) */ {
 public:
  Environement();
  virtual ~Environement();

  Environement(const Environement& from);

  inline Environement& operator=(const Environement& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Environement& default_instance();

  static inline const Environement* internal_default_instance() {
    return reinterpret_cast<const Environement*>(
               &_Environement_default_instance_);
  }

  void Swap(Environement* other);

  // implements Message ----------------------------------------------

  inline Environement* New() const PROTOBUF_FINAL { return New(NULL); }

  Environement* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Environement& from);
  void MergeFrom(const Environement& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Environement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Beacon beacons = 5;
  int beacons_size() const;
  void clear_beacons();
  static const int kBeaconsFieldNumber = 5;
  const ::Beacon& beacons(int index) const;
  ::Beacon* mutable_beacons(int index);
  ::Beacon* add_beacons();
  ::google::protobuf::RepeatedPtrField< ::Beacon >*
      mutable_beacons();
  const ::google::protobuf::RepeatedPtrField< ::Beacon >&
      beacons() const;

  // required string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required string latitude = 3;
  bool has_latitude() const;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 3;
  const ::std::string& latitude() const;
  void set_latitude(const ::std::string& value);
  #if LANG_CXX11
  void set_latitude(::std::string&& value);
  #endif
  void set_latitude(const char* value);
  void set_latitude(const char* value, size_t size);
  ::std::string* mutable_latitude();
  ::std::string* release_latitude();
  void set_allocated_latitude(::std::string* latitude);

  // required string longitud = 4;
  bool has_longitud() const;
  void clear_longitud();
  static const int kLongitudFieldNumber = 4;
  const ::std::string& longitud() const;
  void set_longitud(const ::std::string& value);
  #if LANG_CXX11
  void set_longitud(::std::string&& value);
  #endif
  void set_longitud(const char* value);
  void set_longitud(const char* value, size_t size);
  ::std::string* mutable_longitud();
  ::std::string* release_longitud();
  void set_allocated_longitud(::std::string* longitud);

  // required uint32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // required float width = 6;
  bool has_width() const;
  void clear_width();
  static const int kWidthFieldNumber = 6;
  float width() const;
  void set_width(float value);

  // required float length = 7;
  bool has_length() const;
  void clear_length();
  static const int kLengthFieldNumber = 7;
  float length() const;
  void set_length(float value);

  // required float height = 8;
  bool has_height() const;
  void clear_height();
  static const int kHeightFieldNumber = 8;
  float height() const;
  void set_height(float value);

  // @@protoc_insertion_point(class_scope:Environement)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_name();
  void clear_has_name();
  void set_has_latitude();
  void clear_has_latitude();
  void set_has_longitud();
  void clear_has_longitud();
  void set_has_width();
  void clear_has_width();
  void set_has_length();
  void clear_has_length();
  void set_has_height();
  void clear_has_height();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Beacon > beacons_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr latitude_;
  ::google::protobuf::internal::ArenaStringPtr longitud_;
  ::google::protobuf::uint32 id_;
  float width_;
  float length_;
  float height_;
  friend struct  protobuf_model_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Code

// required .Code.Type type = 1;
inline bool Code::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Code::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Code::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Code::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::Code_Type Code::type() const {
  // @@protoc_insertion_point(field_get:Code.type)
  return static_cast< ::Code_Type >(type_);
}
inline void Code::set_type(::Code_Type value) {
  assert(::Code_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Code.type)
}

// required uint32 order = 2;
inline bool Code::has_order() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Code::set_has_order() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Code::clear_has_order() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Code::clear_order() {
  order_ = 0u;
  clear_has_order();
}
inline ::google::protobuf::uint32 Code::order() const {
  // @@protoc_insertion_point(field_get:Code.order)
  return order_;
}
inline void Code::set_order(::google::protobuf::uint32 value) {
  set_has_order();
  order_ = value;
  // @@protoc_insertion_point(field_set:Code.order)
}

// repeated float data = 3;
inline int Code::data_size() const {
  return data_.size();
}
inline void Code::clear_data() {
  data_.Clear();
}
inline float Code::data(int index) const {
  // @@protoc_insertion_point(field_get:Code.data)
  return data_.Get(index);
}
inline void Code::set_data(int index, float value) {
  data_.Set(index, value);
  // @@protoc_insertion_point(field_set:Code.data)
}
inline void Code::add_data(float value) {
  data_.Add(value);
  // @@protoc_insertion_point(field_add:Code.data)
}
inline const ::google::protobuf::RepeatedField< float >&
Code::data() const {
  // @@protoc_insertion_point(field_list:Code.data)
  return data_;
}
inline ::google::protobuf::RepeatedField< float >*
Code::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:Code.data)
  return &data_;
}

// -------------------------------------------------------------------

// Point

// required float x = 1;
inline bool Point::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Point::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Point::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Point::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Point::x() const {
  // @@protoc_insertion_point(field_get:Point.x)
  return x_;
}
inline void Point::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Point.x)
}

// required float y = 2;
inline bool Point::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Point::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Point::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Point::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Point::y() const {
  // @@protoc_insertion_point(field_get:Point.y)
  return y_;
}
inline void Point::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Point.y)
}

// required float z = 3;
inline bool Point::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Point::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Point::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Point::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float Point::z() const {
  // @@protoc_insertion_point(field_get:Point.z)
  return z_;
}
inline void Point::set_z(float value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:Point.z)
}

// -------------------------------------------------------------------

// Beacon

// required uint32 id = 1;
inline bool Beacon::has_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Beacon::set_has_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Beacon::clear_has_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Beacon::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 Beacon::id() const {
  // @@protoc_insertion_point(field_get:Beacon.id)
  return id_;
}
inline void Beacon::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Beacon.id)
}

// required string uuid = 2;
inline bool Beacon::has_uuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Beacon::set_has_uuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Beacon::clear_has_uuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Beacon::clear_uuid() {
  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_uuid();
}
inline const ::std::string& Beacon::uuid() const {
  // @@protoc_insertion_point(field_get:Beacon.uuid)
  return uuid_.GetNoArena();
}
inline void Beacon::set_uuid(const ::std::string& value) {
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Beacon.uuid)
}
#if LANG_CXX11
inline void Beacon::set_uuid(::std::string&& value) {
  set_has_uuid();
  uuid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Beacon.uuid)
}
#endif
inline void Beacon::set_uuid(const char* value) {
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Beacon.uuid)
}
inline void Beacon::set_uuid(const char* value, size_t size) {
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Beacon.uuid)
}
inline ::std::string* Beacon::mutable_uuid() {
  set_has_uuid();
  // @@protoc_insertion_point(field_mutable:Beacon.uuid)
  return uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Beacon::release_uuid() {
  // @@protoc_insertion_point(field_release:Beacon.uuid)
  clear_has_uuid();
  return uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Beacon::set_allocated_uuid(::std::string* uuid) {
  if (uuid != NULL) {
    set_has_uuid();
  } else {
    clear_has_uuid();
  }
  uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uuid);
  // @@protoc_insertion_point(field_set_allocated:Beacon.uuid)
}

// required float snr = 3;
inline bool Beacon::has_snr() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Beacon::set_has_snr() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Beacon::clear_has_snr() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Beacon::clear_snr() {
  snr_ = 0;
  clear_has_snr();
}
inline float Beacon::snr() const {
  // @@protoc_insertion_point(field_get:Beacon.snr)
  return snr_;
}
inline void Beacon::set_snr(float value) {
  set_has_snr();
  snr_ = value;
  // @@protoc_insertion_point(field_set:Beacon.snr)
}

// required .Point point = 4;
inline bool Beacon::has_point() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Beacon::set_has_point() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Beacon::clear_has_point() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Beacon::clear_point() {
  if (point_ != NULL) point_->::Point::Clear();
  clear_has_point();
}
inline const ::Point& Beacon::point() const {
  // @@protoc_insertion_point(field_get:Beacon.point)
  return point_ != NULL ? *point_
                         : *::Point::internal_default_instance();
}
inline ::Point* Beacon::mutable_point() {
  set_has_point();
  if (point_ == NULL) {
    point_ = new ::Point;
  }
  // @@protoc_insertion_point(field_mutable:Beacon.point)
  return point_;
}
inline ::Point* Beacon::release_point() {
  // @@protoc_insertion_point(field_release:Beacon.point)
  clear_has_point();
  ::Point* temp = point_;
  point_ = NULL;
  return temp;
}
inline void Beacon::set_allocated_point(::Point* point) {
  delete point_;
  point_ = point;
  if (point) {
    set_has_point();
  } else {
    clear_has_point();
  }
  // @@protoc_insertion_point(field_set_allocated:Beacon.point)
}

// required .Code code = 5;
inline bool Beacon::has_code() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Beacon::set_has_code() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Beacon::clear_has_code() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Beacon::clear_code() {
  if (code_ != NULL) code_->::Code::Clear();
  clear_has_code();
}
inline const ::Code& Beacon::code() const {
  // @@protoc_insertion_point(field_get:Beacon.code)
  return code_ != NULL ? *code_
                         : *::Code::internal_default_instance();
}
inline ::Code* Beacon::mutable_code() {
  set_has_code();
  if (code_ == NULL) {
    code_ = new ::Code;
  }
  // @@protoc_insertion_point(field_mutable:Beacon.code)
  return code_;
}
inline ::Code* Beacon::release_code() {
  // @@protoc_insertion_point(field_release:Beacon.code)
  clear_has_code();
  ::Code* temp = code_;
  code_ = NULL;
  return temp;
}
inline void Beacon::set_allocated_code(::Code* code) {
  delete code_;
  code_ = code;
  if (code) {
    set_has_code();
  } else {
    clear_has_code();
  }
  // @@protoc_insertion_point(field_set_allocated:Beacon.code)
}

// required bool enabled = 6;
inline bool Beacon::has_enabled() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Beacon::set_has_enabled() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Beacon::clear_has_enabled() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Beacon::clear_enabled() {
  enabled_ = false;
  clear_has_enabled();
}
inline bool Beacon::enabled() const {
  // @@protoc_insertion_point(field_get:Beacon.enabled)
  return enabled_;
}
inline void Beacon::set_enabled(bool value) {
  set_has_enabled();
  enabled_ = value;
  // @@protoc_insertion_point(field_set:Beacon.enabled)
}

// optional string name = 7;
inline bool Beacon::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Beacon::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Beacon::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Beacon::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Beacon::name() const {
  // @@protoc_insertion_point(field_get:Beacon.name)
  return name_.GetNoArena();
}
inline void Beacon::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Beacon.name)
}
#if LANG_CXX11
inline void Beacon::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Beacon.name)
}
#endif
inline void Beacon::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Beacon.name)
}
inline void Beacon::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Beacon.name)
}
inline ::std::string* Beacon::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:Beacon.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Beacon::release_name() {
  // @@protoc_insertion_point(field_release:Beacon.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Beacon::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Beacon.name)
}

// -------------------------------------------------------------------

// Environement

// required uint32 id = 1;
inline bool Environement::has_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Environement::set_has_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Environement::clear_has_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Environement::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 Environement::id() const {
  // @@protoc_insertion_point(field_get:Environement.id)
  return id_;
}
inline void Environement::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Environement.id)
}

// required string name = 2;
inline bool Environement::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Environement::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Environement::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Environement::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Environement::name() const {
  // @@protoc_insertion_point(field_get:Environement.name)
  return name_.GetNoArena();
}
inline void Environement::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Environement.name)
}
#if LANG_CXX11
inline void Environement::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Environement.name)
}
#endif
inline void Environement::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Environement.name)
}
inline void Environement::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Environement.name)
}
inline ::std::string* Environement::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:Environement.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Environement::release_name() {
  // @@protoc_insertion_point(field_release:Environement.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Environement::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Environement.name)
}

// required string latitude = 3;
inline bool Environement::has_latitude() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Environement::set_has_latitude() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Environement::clear_has_latitude() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Environement::clear_latitude() {
  latitude_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_latitude();
}
inline const ::std::string& Environement::latitude() const {
  // @@protoc_insertion_point(field_get:Environement.latitude)
  return latitude_.GetNoArena();
}
inline void Environement::set_latitude(const ::std::string& value) {
  set_has_latitude();
  latitude_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Environement.latitude)
}
#if LANG_CXX11
inline void Environement::set_latitude(::std::string&& value) {
  set_has_latitude();
  latitude_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Environement.latitude)
}
#endif
inline void Environement::set_latitude(const char* value) {
  set_has_latitude();
  latitude_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Environement.latitude)
}
inline void Environement::set_latitude(const char* value, size_t size) {
  set_has_latitude();
  latitude_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Environement.latitude)
}
inline ::std::string* Environement::mutable_latitude() {
  set_has_latitude();
  // @@protoc_insertion_point(field_mutable:Environement.latitude)
  return latitude_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Environement::release_latitude() {
  // @@protoc_insertion_point(field_release:Environement.latitude)
  clear_has_latitude();
  return latitude_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Environement::set_allocated_latitude(::std::string* latitude) {
  if (latitude != NULL) {
    set_has_latitude();
  } else {
    clear_has_latitude();
  }
  latitude_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), latitude);
  // @@protoc_insertion_point(field_set_allocated:Environement.latitude)
}

// required string longitud = 4;
inline bool Environement::has_longitud() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Environement::set_has_longitud() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Environement::clear_has_longitud() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Environement::clear_longitud() {
  longitud_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_longitud();
}
inline const ::std::string& Environement::longitud() const {
  // @@protoc_insertion_point(field_get:Environement.longitud)
  return longitud_.GetNoArena();
}
inline void Environement::set_longitud(const ::std::string& value) {
  set_has_longitud();
  longitud_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Environement.longitud)
}
#if LANG_CXX11
inline void Environement::set_longitud(::std::string&& value) {
  set_has_longitud();
  longitud_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Environement.longitud)
}
#endif
inline void Environement::set_longitud(const char* value) {
  set_has_longitud();
  longitud_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Environement.longitud)
}
inline void Environement::set_longitud(const char* value, size_t size) {
  set_has_longitud();
  longitud_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Environement.longitud)
}
inline ::std::string* Environement::mutable_longitud() {
  set_has_longitud();
  // @@protoc_insertion_point(field_mutable:Environement.longitud)
  return longitud_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Environement::release_longitud() {
  // @@protoc_insertion_point(field_release:Environement.longitud)
  clear_has_longitud();
  return longitud_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Environement::set_allocated_longitud(::std::string* longitud) {
  if (longitud != NULL) {
    set_has_longitud();
  } else {
    clear_has_longitud();
  }
  longitud_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), longitud);
  // @@protoc_insertion_point(field_set_allocated:Environement.longitud)
}

// repeated .Beacon beacons = 5;
inline int Environement::beacons_size() const {
  return beacons_.size();
}
inline void Environement::clear_beacons() {
  beacons_.Clear();
}
inline const ::Beacon& Environement::beacons(int index) const {
  // @@protoc_insertion_point(field_get:Environement.beacons)
  return beacons_.Get(index);
}
inline ::Beacon* Environement::mutable_beacons(int index) {
  // @@protoc_insertion_point(field_mutable:Environement.beacons)
  return beacons_.Mutable(index);
}
inline ::Beacon* Environement::add_beacons() {
  // @@protoc_insertion_point(field_add:Environement.beacons)
  return beacons_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Beacon >*
Environement::mutable_beacons() {
  // @@protoc_insertion_point(field_mutable_list:Environement.beacons)
  return &beacons_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Beacon >&
Environement::beacons() const {
  // @@protoc_insertion_point(field_list:Environement.beacons)
  return beacons_;
}

// required float width = 6;
inline bool Environement::has_width() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Environement::set_has_width() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Environement::clear_has_width() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Environement::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline float Environement::width() const {
  // @@protoc_insertion_point(field_get:Environement.width)
  return width_;
}
inline void Environement::set_width(float value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:Environement.width)
}

// required float length = 7;
inline bool Environement::has_length() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Environement::set_has_length() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Environement::clear_has_length() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Environement::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline float Environement::length() const {
  // @@protoc_insertion_point(field_get:Environement.length)
  return length_;
}
inline void Environement::set_length(float value) {
  set_has_length();
  length_ = value;
  // @@protoc_insertion_point(field_set:Environement.length)
}

// required float height = 8;
inline bool Environement::has_height() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Environement::set_has_height() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Environement::clear_has_height() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Environement::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline float Environement::height() const {
  // @@protoc_insertion_point(field_get:Environement.height)
  return height_;
}
inline void Environement::set_height(float value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:Environement.height)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Code_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Code_Type>() {
  return ::Code_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_model_2eproto__INCLUDED
